In [1]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

In [2]:
# 读取示例数据
data = pd.read_csv("smoke.csv")
data

     age  gender smoking  cancer
0   66.2  female      no       0
1   43.9    male      no       0
2   44.7    male      no       1
3   39.3  female      no       0
4   58.7    male     yes       1
5   27.0    male      no       1
6   67.4  female      no       0
7   42.4    male     yes       1
8   53.2  female      no       0
9   47.5  female      no       0
10  64.6  female      no       0
11  29.4  female     yes       1
12  46.8  female      no       0
13  46.2    male      no       1
14  61.3    male     yes       1
15  39.0  female      no       1
16  48.3    male     yes       1
17  41.2  female      no       0
18  50.4  female     yes       1
19  55.8  female     yes       1
20  39.0    male      no       1
21  61.4  female      no       0
22  59.0    male      no       1
23  55.0  female      no       0
24  59.0    male      no       1
25  43.2    male      no       0
26  48.8  female      no       0
27  40.6  female     yes       1
28  47.3    male      no       0
29  55.3  female      no       1
30  43.1    male      no       0
31  46.0  female     yes       1
32  43.1  female      no       1
33  41.5    male      no       1
34  43.3  female      no       0
35  49.9  female     yes       1
36  38.8    male      no       1
37  52.3  female      no       0
38  66.6  female     yes       1
39  57.4  female     yes       1
40  48.1    male      no       1
41  41.1    male      no       0
42  42.5  female      no       0
43  66.9  female     yes       0
44  50.5    male      no       0
45  43.6  female      no       0
46  51.9  female      no       0
47  71.0  female      no       0
48  51.2  female      no       0
49  56.2    male      no       0

In [3]:
# 为data的“gender”和“smoking”分类变量创建虚拟变量

In [4]:
# 查看自变量之间所有相关系数是否有大于0.8的

In [5]:
# 创建构建逻辑回归模型所需的因变量和自变量



# 在自变量里添加一个常量（为了引入截距）

In [6]:
# 构建逻辑回归模型，并进行数据拟合



# 输出拟合结果

In [7]:
# 计算系数的含义